name: Build and Release

on:
  push:
    branches:
      - main  # Adjust the branch as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Reading manifest.JSON file
        id: read_json
        run: |
          if [ -f manifest.json ]; then
            echo "version=$(jq -r .version_number manifest.json)" >> $GITHUB_OUTPUT
          else
            echo "manifest.json not found. Exiting..."
            exit 1
          fi

      - name: Create Zip
        run: |
          zip -r "Komodo_Custom_Suit_Pack_${{ steps.read_json.outputs.version }}.zip" . -x "*.git*" -x "*.github*"


      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.read_json.outputs.version }}
          name: Release ${{ steps.read_json.outputs.version }}
          draft: false
          prerelease: false
          body: |
            KCSP v${{ steps.read_json.outputs.version }} has been released! 🎉
          files: "Komodo_Custom_Suit_Pack_${{ steps.read_json.outputs.version }}.zip"

      - name: Released
        run: |
          echo "Package released: \n${{ fromJSON(steps.create_release.outputs.assets)[0].browser_download_url }}"