name: Build and Release

on:
  push:
    branches:
      - main  # Adjust the branch as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Reading manifest.JSON file
        id: read_json
        run: |
          if [ -f manifest.json ]; then
            echo "version=$(jq -r .version_number manifest.json)" >> $GITHUB_OUTPUT
          else
            echo "manifest.json not found. Exiting..."
            exit 1
          fi

      - name: Create Zip
        run: |
          zip -r "Komodo_Custom_Suit_Pack_${{ steps.read_json.outputs.version }}.zip" . -x "*.git*" -x "*.github*"


      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.read_json.outputs.version }}
          release_name: Release ${{ steps.read_json.outputs.version }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: "./Komodo_Custom_Suit_Pack_${{ steps.read_json.outputs.version }}.zip"
          asset_name: "Komodo_Custom_Suit_Pack_${{ steps.read_json.outputs.version }}.zip"
          asset_content_type: application/zip